export interface Channel {
  id: string;
  name: string;
}

export const channels: Channel[] = [
  { id: "bbb25a", name: "BBB 25 Câmera 1" },
  { id: "bbb25b", name: "BBB 25 Câmera 2" },
  { id: "aie", name: "A&E" },
  { id: "adultswim", name: "Adult Swim" },
  { id: "amc", name: "AMC" },
  { id: "animalplanet", name: "Animal Planet" },
  { id: "arte1", name: "Arte 1" },
  { id: "axn", name: "AXN" },
  { id: "band", name: "Band" },
  { id: "bandnews", name: "Band News" },
  { id: "bandsports", name: "Band Sports" },
  { id: "bis", name: "BIS" },
  { id: "canalbrasil", name: "Canal Brasil" },
  { id: "cancaonova", name: "Canção Nova" },
  { id: "cartoon", name: "Cartoon Network" },
  { id: "cartoonito", name: "Cartoonito" },
  { id: "cinecanal", name: "Cinecanal" },
  { id: "cinemax", name: "Cinemax" },
  { id: "cnnbrasil", name: "CNN Brasil" },
  { id: "combate", name: "Combate" },
  { id: "comedycentral", name: "Comedy Central" },
  { id: "curta", name: "Curta!" },
  { id: "discoverychannel", name: "Discovery Channel" },
  { id: "discoveryhomeihealth", name: "Discovery Home & Health" },
  { id: "discoverykids", name: "Discovery Kids" },
  { id: "discoverysience", name: "Discovery Science" },
  { id: "discoverytheater", name: "Discovery Theater" },
  { id: "discoveryturbo", name: "Discovery Turbo" },
  { id: "discoveryworld", name: "Discovery World" },
  { id: "disney", name: "Disney Channel" },
  { id: "canale", name: "Canal E!" },
  { id: "espn", name: "ESPN" },
  { id: "espn2", name: "ESPN 2" },
  { id: "espn3", name: "ESPN 3" },
  { id: "espn4", name: "ESPN 4" },
  { id: "espn5", name: "ESPN 5" },
  { id: "espn6", name: "ESPN 6" },
  { id: "fishtv", name: "Fish TV" },
  { id: "foodnetwork", name: "Food Network" },
  { id: "fx", name: "FX" },
  { id: "globonews", name: "Globo News" },
  { id: "bobonordeste", name: "Globo Nordeste" },
  { id: "boborj", name: "Globo RJ" },
  { id: "bobosp", name: "Globo SP" },
  { id: "gloob", name: "Gloob" }
];