export interface Channel {
  id: string;
  name: string;
}

export const channels: Channel[] = [
  { id: "bbb25a", name: "BBB 25 Câmera 1" },
  { id: "bbb25b", name: "BBB 25 Câmera 2" },
  { id: "aie", name: "A&E" },
  { id: "adultswim", name: "Adult Swim" },
  { id: "amc", name: "AMC" },
  { id: "animalplanet", name: "Animal Planet" },
  { id: "arte1", name: "Arte 1" },
  { id: "axn", name: "AXN" },
  { id: "band", name: "Band" },
  { id: "bandnews", name: "Band News" },
  { id: "bandsports", name: "Band Sports" },
  { id: "bis", name: "BIS" },
  { id: "canalbrasil", name: "Canal Brasil" },
  { id: "cancaonova", name: "Canção Nova" },
  { id: "cartoon", name: "Cartoon Network" },
  { id: "cartoonito", name: "Cartoonito" },
  { id: "cinecanal", name: "Cinecanal" },
  { id: "cinemax", name: "Cinemax" },
  { id: "cnnbrasil", name: "CNN Brasil" },
  { id: "combate", name: "Combate" },
  { id: "comedycentral", name: "Comedy Central" },
  { id: "curta", name: "Curta!" },
  { id: "discoverychannel", name: "Discovery Channel" },
  { id: "discoveryhomeihealth", name: "Discovery Home & Health" },
  { id: "discoverykids", name: "Discovery Kids" },
  { id: "discoverysience", name: "Discovery Science" },
  { id: "discoverytheater", name: "Discovery Theater" },
  { id: "discoveryturbo", name: "Discovery Turbo" },
  { id: "discoveryworld", name: "Discovery World" },
  { id: "disney", name: "Disney Channel" },
  { id: "canale", name: "Canal E!" },
  { id: "espn", name: "ESPN" },
  { id: "espn2", name: "ESPN 2" },
  { id: "espn3", name: "ESPN 3" },
  { id: "espn4", name: "ESPN 4" },
  { id: "espn5", name: "ESPN 5" },
  { id: "espn6", name: "ESPN 6" },
  { id: "fishtv", name: "Fish TV" },
  { id: "foodnetwork", name: "Food Network" },
  { id: "fx", name: "FX" },
  { id: "globonews", name: "Globo News" },
  { id: "bobonordeste", name: "Globo Nordeste" },
  { id: "boborj", name: "Globo RJ" },
  { id: "bobosp", name: "Globo SP" },
  { id: "gloob", name: "Gloob" },
  { id: "gloobinho", name: "Gloobinho" },
  { id: "gnt", name: "GNT" },
  { id: "hbo", name: "HBO" },
  { id: "hbo2", name: "HBO 2" },
  { id: "hbofamily", name: "HBO Family" },
  { id: "hbomundi", name: "HBO Mundi" },
  { id: "hboplus", name: "HBO Plus" },
  { id: "hbopop", name: "HBO Pop" },
  { id: "hbosignature", name: "HBO Signature" },
  { id: "hboxtreme", name: "HBO Xtreme" },
  { id: "hgtv", name: "HGTV" },
  { id: "history", name: "History" },
  { id: "history2", name: "History 2" },
  { id: "investigacaodiscovery", name: "Investigação Discovery" },
  { id: "lifetime", name: "Lifetime" },
  { id: "megapix", name: "Megapix" },
  { id: "modoviagem", name: "Modo Viagem" },
  { id: "mtv", name: "MTV" },
  { id: "mtvlive", name: "MTV Live" },
  { id: "multishow", name: "Multishow" },
  { id: "natgeo", name: "National Geographic" },
  { id: "nickjr", name: "Nick Jr." },
  { id: "nick", name: "Nickelodeon" },
  { id: "nossofutebol", name: "Nosso Futebol" },
  { id: "off", name: "OFF" },
  { id: "paramount", name: "Paramount" },
  { id: "primeboxbrazil", name: "Prime Box Brazil" },
  { id: "recordnews", name: "Record News" },
  { id: "record", name: "Record TV" },
  { id: "redetv", name: "RedeTV!" },
  { id: "saboriarte", name: "Sabor & Arte" },
  { id: "sbt", name: "SBT" },
  { id: "sony", name: "Sony" },
  { id: "sonymovies", name: "Sony Movies" },
  { id: "space", name: "Space" },
  { id: "sportv1", name: "SporTV 1" },
  { id: "sportv2", name: "SporTV 2" },
  { id: "sportv3", name: "SporTV 3" },
  { id: "starchannel", name: "Star Channel" },
  { id: "studiouniversal", name: "Studio Universal" },
  { id: "telecineaction", name: "Telecine Action" },
  { id: "telecinecult", name: "Telecine Cult" },
  { id: "telecinefun", name: "Telecine Fun" },
  { id: "telecinepipoca", name: "Telecine Pipoca" },
  { id: "telecinepremium", name: "Telecine Premium" },
  { id: "telecinetouch", name: "Telecine Touch" },
  { id: "cnbcbrasil", name: "CNBC Brasil" },
  { id: "tlc", name: "TLC" },
  { id: "tnt", name: "TNT" },
  { id: "tntnovelas", name: "TNT Novelas" },
  { id: "tntseries", name: "TNT Séries" },
  { id: "travelboxbrazil", name: "Travel Box Brazil" },
  { id: "ufcfightpass", name: "UFC Fight Pass" },
  { id: "universal", name: "Universal" },
  { id: "usa", name: "USA Network" },
  { id: "viva", name: "Viva" },
  { id: "warner", name: "Warner Channel" }
];
